-- Active: 1725313360174@@localhost@5432@postgres
CREATE TABLE cars(
    id SERIAL PRIMARY KEY,
    mark CHARACTER VARYING(30) NOT NULL, 
    model CHARACTER VARYING(30) NOT NULL, 
    volume CHARACTER VARYING(30) NOT NULL, 
    price CHARACTER VARYING(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
ALTER TABLE cars
ADD COLUMN YEAR CHARACTER VARYING(6),
ADD COLUMN KILOMETERS CHARACTER VARYING(30),
ADD COLUMN POWER CHARACTER VARYING(30),
ADD COLUMN TRANSMISSION CHARACTER VARYING(3),
ADD COLUMN FUEL CHARACTER VARYING(30);

ALTER TABLE cars
ALTER COLUMN YEAR SET DATA TYPE CHARACTER VARYING(30),
ALTER COLUMN TRANSMISSION SET DATA TYPE CHARACTER VARYING(30);

ALTER TABLE cars
ADD COLUMN OWNERS CHARACTER VARYING(30),
ADD COLUMN DRIVE CHARACTER VARYING(30);